base_config:
- configs/original/variance.yaml

dictionaries:
  zh: dictionaries/opencpop-extension.txt
all_phonemes: [AP, SP]
extra_phonemes:
merged_phoneme_groups: []
lang_phoneme_separator: [/]

datasets:
  - raw_data_dir: data/xxx1/raw
    speaker: speaker1
    spk_id: 0
    language: zh
    test_prefixes:
    - wav1
    - wav2
    - wav3
    - wav4
    - wav5
    -
binary_data_dir: data/xxx/binary
binarization_args:
  num_workers: 4
  allow_missing_phonemes: true

pe: rmvpe
pe_ckpt: ckpt/rmvpe/model.pt
hnsep: vr
hnsep_ckpt: ckpt/vr/model.pt

use_lang_id: false
num_lang: 1
use_spk_id: true
num_spk: 1

predict_dur: true
predict_pitch: false
predict_energy: false
predict_breathiness: false
predict_voicing: false
predict_tension: false

energy_db_min: -96.0
energy_db_max: -12.0
breathiness_db_min: -96.0
breathiness_db_max: -20.0
voicing_db_min: -96.0
voicing_db_max: -12.0
tension_logit_min: -10.0
tension_logit_max: 10.0

enc_ffn_kernel_size: 3
use_rope: true
hidden_size: 256
dur_prediction_args:
  arch: resnet
  hidden_size: 256
  dropout: 0.1
  num_layers: 5
  kernel_size: 3
  log_offset: 1.0
  loss_type: mse
  lambda_pdur_loss: 0.3
  lambda_wdur_loss: 1.0
  lambda_sdur_loss: 3.0

use_melody_encoder: false
melody_encoder_args:
  hidden_size: 128
  enc_layers: 4
use_glide_embed: false
glide_types:
- up
- down
glide_embed_scale: 11.31370849898476
diffusion_type: reflow
pitch_prediction_args:
  pitd_norm_min: -8.0
  pitd_norm_max: 8.0
  pitd_clip_min: -12.0
  pitd_clip_max: 12.0
  repeat_bins: 64
  backbone_type: lynxnet2
  backbone_args:
    num_layers: 6
    num_channels: 512
    dropout_rate: 0.0
variances_prediction_args:
  total_repeat_bins: 48
  backbone_type: lynxnet2
  backbone_args:
    num_layers: 6
    num_channels: 384
    dropout_rate: 0.0
lambda_dur_loss: 1.0
lambda_pitch_loss: 1.0
lambda_var_loss: 1.0
optimizer_args:
  optimizer_cls: modules.optimizer.muon.Muon_AdamW
  lr: 0.0006
  muon_args:
    weight_decay: 0.1
  adamw_args:
    weight_decay: 0.0
lr_scheduler_args:
  step_size: 5000
  gamma: 0.8

max_batch_frames: 80000
max_batch_size: 48
max_updates: 50ep
num_valid_plots: 1
val_check_interval: 5ep
num_ckpt_keep: 50
permanent_ckpt_start: 60000
permanent_ckpt_interval: 10000
pl_trainer_devices: auto
pl_trainer_precision: bf16-mixed

lora:
  alpha: 16
  base_ckpt: finetune_ckpt_path
  enabled: true
  merge_before_export: true
  rank: 8
  target_modules:
  - ^fs2\.
  train_bias: true
